repos:
-   repo: local
    hooks:
    -   id: pytest
        name: Run Pytest
        entry: pytest --cov=. --cov-fail-under=80
        language: system
        pass_filenames: false
        always_run: true